Feat/dockerize
Uier/examhub pull request #19
Opened 2021-09-05 15:33 UTC by Uier

2021-09-06 01:04 UTC, Bogay requested changes

2021-09-06 01:04 UTC, Bogay commented on docker-compose.yml
> +      - db
應該要把 NODE_ENV 設成 production？
還是說 .env 裡面已經設定啦？

2021-09-06 01:04 UTC, Bogay commented on server/src/models/index.ts
> +      attemptConnection(s)
這個 arrow function 應該是多餘的？

2021-09-06 17:06 UTC, Uier commented on docker-compose.yml
> +      - db
放 .env 吧，我寫在 README

2021-09-06 17:11 UTC, Uier commented on server/src/models/index.ts
> +      attemptConnection(s)
fixed

2021-09-07 09:48 UTC, Bogay approved these changes

2021-09-07 09:48 UTC, Bogay approved these changes

2021-09-28 13:15 UTC, merged